# Generated by Django 3.1.7 on 2021-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='username',
            field=models.CharField(default='pending', max_length=20),
            preserve_default=False,
        ),
    ]
